-- Test coordinator: require all FactorioTest files here.

require("tests.smoke_test")
require("tests.milestone0_test")
require("tests.milestone1_test")
require("tests.milestone2_test")
require("tests.milestone4_test")
require("tests.milestone5_test")
require("tests.milestone6_test")
require("tests.squirrels.render_test")
require("tests.squirrels.carrying_test")
require("tests.squirrels.stash_test")
require("tests.squirrels.belt_test")
require("tests.squirrels.population_test")
require("tests.regions.math_test")
require("tests.regions.store_test")
require("tests.regions.recompute_test")
require("tests.regions.cluster_test")
require("tests.regions.module_test")
require("tests.habitat.world_test")
require("tests.habitat.lifecycle_test")
require("tests.habitat.seeding_test")
require("tests.habitat.tutorials_test")
require("tests.feeders.inventory_test")
require("tests.feeders.module_test")
